### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by wijiler** [dogegarden/dogehouse.js#26]
I made my bot but I have no idea how to get it on dogehouse also it doesn't  have the syntax listed I know it's easy to figure it out but I just need some more clarity on things

**Comment by Lare1** [comment]
Yes please more documentation and examples

**Comment by JustM3Dev** [comment]
There's a tutorial series on setting up a bot here:
 https://youtu.be/rRWfT12yjI8

And some examples in the /examples folder.
For the rest you can just look in the src folder.

**Comment by HoloPanio** [comment]
> There's a tutorial series on setting up a bot here:
> https://youtu.be/rRWfT12yjI8
> 
> And some examples in the /examples folder.
> For the rest you can just look in the src folder.
> 
> Oh and a documentation on the api is on the way!

Thank you for linking them to the first tutorial.  If you have any further questions, feel free to reopen this issue, or shoot us a message on the [discord](https://discord.gg/pPaXCRrVrh).
