### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by dragonismcode** [dogegarden/dogehouse.js#27]
I can't figure out what is causing this.. I've tried this on my main PC and on CodeSandbox but this error always comes up.

I'm using the exact same code as [this](https://github.com/dogegarden/dogehouse.js/blob/master/examples/popular-rooms.js) example.
And I have made a .env file with my Dogehouse token & refresh token but it all just won't work.

I've installed and used dotenv, but still no luck.

I can log in just fine with the same tokens using previous dogehouse-js v1.

### index.js
```js
const { Client } = require("dogehouse.js");
const app = new Client();

app
  .connect(process.env.DOGEHOUSE_TOKEN, process.env.DOGEHOUSE_REFRESH_TOKEN)
  .then(async () => {
    console.log("Bot connected.");
    console.log(await app.rooms.top); // Log all of your top rooms to console
  });

```

### .env
```
DOGEHOUSE_TOKEN=token
DOGEHOUSE_REFRESH_TOKEN=token
```

### Error
```js
sandbox/node_modules/dogehouse.js/src/Client.js:179
        _onMessageOnceQueue = new Map();
                            ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/sandbox/node_modules/dogehouse.js/index.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Any help is greatly appreciated! I really want to upgrade [BenBot](https://github.com/dragonismcode/benbot) to dogehouse.js 2.0.1.

**Comment by boydmeyer** [comment]
did you

const dotenv = require("dotenv").config();

**Comment by ebarracchia** [comment]
Please add this at the top of your file

require('dotenv').config()

**Comment by HoloPanio** [comment]
Hello,

After a considerable amount of time and debugging, I can conclude that the reason that you are being thrown this error because you are not using a supported version of node.js.  If you could please provide your version of node.js, that would be greatly appreciated.

**Comment by ebarracchia** [comment]
@dragonismcode  Type command “node —version” to check the Node’s version

**Comment by shadowfiles01** [comment]
You will need to be using Node v14+

**Comment by JackCrispy** [comment]
Closing, use node 14+.
