### ISSUE TITLE
Voice Support?

### ISSUE THREAD

**Issue by Atlas7005** [dogegarden/dogehouse.js#28]
It would be nice if there was voice support, for stuff like Music Bots.

**Comment by dragonismcode** [comment]
@HoloPanio has it working just doesn't want to share it yet. 😄

**Comment by Atlas7005** [comment]
Meanie :(

**Comment by HoloPanio** [comment]
I would like to state for the record that I am not reluctant to share the source code as I have not finished writing in audio support.  Audio support will be rolling out either today or tomorrow depending on how the debugging process goes.  If it goes will then I will be releasing it to staging to then be pushed to master.
