### ISSUE TITLE
how to get the room token in dogehouse

### ISSUE THREAD

**Issue by akionsight** [dogegarden/dogehouse.js#42]
to  join a room, we need the ROOM TOKEN as written in the comments in examples, but I am not able to figure out where to get the same, I looked in the comments and the docs without avail, any help would be great

**Comment by ebarracchia** [comment]
These are the steps
1) Go to DogeHouse
2) Open Developer options (F12 or Ctrl+Shift+I)
3) Go to Application > Local Storage > dogehouse.tv
4) Copy your token and refresh-token and put them in an .env file:
DOGEHOUSE_TOKEN=<token>
DOGEHOUSE_REFRESH_TOKEN=<refresh-token>

[Link](https://github.com/dogegarden/dogehouse.js)

**Comment by ErlendCat** [comment]
I recommend that you use the room selector I made: [Example](https://github.com/dogegarden/dogehouse.js/blob/master/examples/popular-rooms-selector.js).

Or else you can always find the room-ID in the adress bar.
![Finding the room-ID](https://user-images.githubusercontent.com/49862976/112760995-4dcf6c00-8ff9-11eb-82e8-669be5d8ddca.png)

**Comment by akionsight** [comment]
thanks for helping me out
