### ISSUE TITLE
type-errors on connect

### ISSUE THREAD

**Issue by plunched** [dogegarden/dogehouse.js#52]
when I try connecting to the api using the following method: 
```ts
app.connect(token, refresh).then(async () => {
  console.log("logged in");
});
```

it throws me a lot of type errors, they are pretty much all in the **src/util/types/index.d.ts** file of the npm package

this is with the **2.0.5** version and the token and refresh are correct.

**Comment by HoloPanio** [comment]
Also an issue we'll be fixing in the new version. There are a lot of things that broke when the DogeHouse api was updated.

**Comment by plunched** [comment]
yep I noticed, I talked to you on dogehouse last night
