### ISSUE TITLE
Wouldn't it be better to create an Event class?

### ISSUE THREAD

**Issue by plunched** [dogegarden/dogehouse.js#54]
Wouldn't it be better to create an event class, with all its parameters instead of a property, like it now is.

I would think that it would help a lot especially with things like 
- auto-complete
- less errors (typo checking)
- etc.

I would be open to code this up as well.

**Comment by HoloPanio** [comment]
It is already integrated into version 3.0 which the first viable beta should be coming out within the next couple of days.
