### ISSUE TITLE
tsconfig

### ISSUE THREAD

**Issue by Lofu1** [dogegarden/dogehouse.js#55]
I'm getting an error on tsconfig on the first line its underlined the { and when i start im getting this error

this._cooldown = options.cooldown ?? defaultChatCooldown;
SyntaxError: Unexpected token '?'

**Comment by plunched** [comment]
holo is fixing this in his 3.0 patch, this issue will probably be tackled by then.

**Comment by HoloPanio** [comment]
Please update your node.js and if you have any issues, be sure to let us know.
